//! Big-font mode face: the embedded fusion-pixel glyph atlas, the
//! cluster → glyph mapping and the tofu fallback (docs/big-font-mode.md
//! §3.3/§3.4/§4). Consumers: the T-11 engine strip kinematics and the T-12
//! renderer; the asset itself is generated by tools/gen-bigfont (T-9) and
//! its format is documented in docs/bigfont-asset-format.md.

pub mod asset;
pub mod raster;

pub use asset::{AssetError, BigFontAsset, Glyph};

/// The committed zh-Hans atlas, embedded at compile time so builds stay
/// offline and `cargo install` needs no font downloads.
pub const EMBEDDED_ZH_HANS: &[u8] = include_bytes!("../../assets/bigfont-12px-zh-hans.bin");

/// What a char or grapheme cluster resolves to: an asset glyph, or the
/// 12×12 hollow tofu box that keeps the strip layout intact for missing
/// glyphs (§3.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResolvedGlyph<'a> {
    Found(Glyph<'a>),
    Tofu,
}

impl ResolvedGlyph<'_> {
    /// Glyph width in pixel columns: 6 or 12 (tofu is fullwidth).
    pub fn width_px(&self) -> u16 {
        match self {
            Self::Found(g) => g.width_px(),
            Self::Tofu => asset::WIDTH_FULL_PX,
        }
    }

    /// Pixel state at (`x`, `y`); `y` = 0 is the topmost of the 12 rows.
    pub fn pixel(&self, x: usize, y: usize) -> bool {
        debug_assert!(x < self.width_px() as usize && y < asset::GLYPH_HEIGHT_PX as usize);
        match self {
            Self::Found(g) => g.pixel(x, y),
            Self::Tofu => {
                let last = asset::WIDTH_FULL_PX as usize - 1;
                x == 0 || y == 0 || x == last || y == last
            }
        }
    }

    pub fn is_tofu(&self) -> bool {
        matches!(self, Self::Tofu)
    }
}

/// The big-font face over one parsed asset.
pub struct BigFontFace<'a> {
    asset: BigFontAsset<'a>,
}

impl BigFontFace<'static> {
    /// The embedded zh-Hans face. Fails only if the committed asset is
    /// corrupt — unit tests parse it on every run, so `Err` here is a
    /// build bug.
    pub fn embedded_zh_hans() -> Result<Self, AssetError> {
        Self::from_bytes(EMBEDDED_ZH_HANS)
    }
}

impl<'a> BigFontFace<'a> {
    pub fn from_bytes(bytes: &'a [u8]) -> Result<Self, AssetError> {
        Ok(Self {
            asset: BigFontAsset::parse(bytes)?,
        })
    }

    pub fn asset(&self) -> &BigFontAsset<'a> {
        &self.asset
    }

    /// Single char → glyph, or tofu when the atlas has no glyph for it.
    pub fn resolve_char(&self, ch: char) -> ResolvedGlyph<'a> {
        match self.asset.lookup(ch) {
            Some(g) => ResolvedGlyph::Found(g),
            None => ResolvedGlyph::Tofu,
        }
    }

    /// Grapheme cluster → exactly one glyph (§3.4): the first codepoint of
    /// the cluster that has a glyph wins; otherwise tofu. Big-mode widths
    /// count glyph pixel columns, deliberately decoupled from the main
    /// mode's unicode-width semantics.
    pub fn resolve_cluster(&self, cluster: &str) -> ResolvedGlyph<'a> {
        for ch in cluster.chars() {
            if let Some(g) = self.asset.lookup(ch) {
                return ResolvedGlyph::Found(g);
            }
        }
        ResolvedGlyph::Tofu
    }
}

#[cfg(test)]
mod tests {
    use super::raster::{Rasterizer, cell_rows};
    use super::*;

    fn face() -> BigFontFace<'static> {
        BigFontFace::embedded_zh_hans().expect("the committed zh-Hans asset must parse")
    }

    #[test]
    fn embedded_face_loads() {
        let f = face();
        assert_eq!(f.asset().glyph_count(), 7188);
        assert!(
            f.asset()
                .provenance()
                .starts_with("source=fusion-pixel-font")
        );
    }

    #[test]
    fn resolve_char_widths() {
        let f = face();
        assert_eq!(f.resolve_char('中').width_px(), 12);
        assert_eq!(f.resolve_char('A').width_px(), 6);
        assert_eq!(
            f.resolve_char(' ').width_px(),
            6,
            "space is a real glyph, not tofu"
        );
        assert!(!f.resolve_char(' ').is_tofu());
        assert!(f.resolve_char('🚀').is_tofu());
        assert_eq!(f.resolve_char('🚀').width_px(), 12, "tofu is fullwidth");
        assert!(
            f.resolve_char('働').is_tofu(),
            "ja-only hanzi are not in the zh-Hans atlas"
        );
    }

    #[test]
    fn tofu_is_a_hollow_box() {
        let f = face();
        let tofu = f.resolve_char('\u{1f680}');
        assert!(tofu.pixel(0, 0) && tofu.pixel(11, 0) && tofu.pixel(0, 11) && tofu.pixel(11, 11));
        assert!(tofu.pixel(5, 0) && tofu.pixel(0, 5) && tofu.pixel(11, 5) && tofu.pixel(5, 11));
        assert!(!tofu.pixel(5, 5) && !tofu.pixel(1, 1) && !tofu.pixel(10, 10));
    }

    /// §3.4: the cluster maps to its first codepoint that has a glyph;
    /// clusters with no glyphed codepoint at all become tofu.
    #[test]
    fn clusters_map_to_first_glyphed_codepoint() {
        let f = face();
        // e + combining acute → the glyph for 'e' (halfwidth).
        assert_eq!(f.resolve_cluster("e\u{301}"), f.resolve_char('e'));
        assert_eq!(f.resolve_cluster("e\u{301}").width_px(), 6);
        // Plain CJK cluster.
        assert_eq!(f.resolve_cluster("中"), f.resolve_char('中'));
        // ZWJ family, flag pair and lone emoji: nothing glyphed → tofu,
        // one fullwidth cell block, scrolling never breaks.
        assert!(
            f.resolve_cluster("👨\u{200d}👩\u{200d}👧\u{200d}👦")
                .is_tofu()
        );
        assert!(f.resolve_cluster("🇯🇵").is_tofu());
        assert!(f.resolve_cluster("🚀").is_tofu());
        // Degenerate empty cluster → tofu.
        assert!(f.resolve_cluster("").is_tofu());
    }

    /// Checklist: "No allocation per glyph lookup on the render path beyond
    /// the reused row buffer" — measured with a counting allocator that is
    /// only armed on the calling thread, so parallel tests cannot pollute
    /// the count.
    #[test]
    fn render_path_is_allocation_free() {
        let f = face();
        let mut raster = Rasterizer::new();
        // Warm-up: size the reused row buffer for the widest measured case
        // (fullwidth at scale 3 = 36 cells).
        let yi = f.resolve_char('一');
        for row in 0..cell_rows(3) {
            std::hint::black_box(raster.render_row(&yi, 3, row));
        }

        let allocations = alloc_probe::count(|| {
            for _ in 0..100 {
                let cluster = f.resolve_cluster("e\u{301}");
                std::hint::black_box(&cluster);
                for row in 0..cell_rows(3) {
                    std::hint::black_box(raster.render_row(&cluster, 3, row));
                }
                let kou = f.resolve_char('口');
                for row in 0..cell_rows(2) {
                    std::hint::black_box(raster.render_row(&kou, 2, row));
                }
                let tofu = f.resolve_char('🚀');
                for row in 0..cell_rows(1) {
                    std::hint::black_box(raster.render_row(&tofu, 1, row));
                }
            }
        });
        assert_eq!(
            allocations, 0,
            "lookups + row renders must not allocate once the buffer is warm"
        );
    }

    /// Allocation probe: a pass-through global allocator that counts
    /// allocations of the current thread while armed. Const-initialized
    /// thread locals keep the counting itself allocation-free.
    mod alloc_probe {
        use std::alloc::{GlobalAlloc, Layout, System};
        use std::cell::Cell;

        struct Counting;

        thread_local! {
            static COUNT: Cell<usize> = const { Cell::new(0) };
            static ARMED: Cell<bool> = const { Cell::new(false) };
        }

        impl Counting {
            fn tick() {
                if ARMED.with(Cell::get) {
                    COUNT.with(|c| c.set(c.get() + 1));
                }
            }
        }

        // SAFETY: pass-through to the system allocator; the counter is
        // thread-local and only touched through const-initialized cells.
        unsafe impl GlobalAlloc for Counting {
            unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
                Self::tick();
                unsafe { System.alloc(layout) }
            }
            unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
                unsafe { System.dealloc(ptr, layout) }
            }
            unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
                Self::tick();
                unsafe { System.realloc(ptr, layout, new_size) }
            }
        }

        #[global_allocator]
        static GLOBAL: Counting = Counting;

        /// Runs `f` with counting armed on this thread; returns the number
        /// of allocations it made.
        pub fn count(f: impl FnOnce()) -> usize {
            COUNT.with(|c| c.set(0));
            ARMED.with(|c| c.set(true));
            f();
            ARMED.with(|c| c.set(false));
            COUNT.with(Cell::get)
        }
    }
}
